# Generated by Django 2.1.5 on 2019-11-30 02:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.TextField()),
                ('response_code', models.TextField()),
                ('graphql_operation', models.TextField()),
                ('graphql_variables', models.TextField()),
                ('environ_useragent', models.TextField()),
                ('environ_username', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
